# 机器人客户端配置文件

# 机器人配置
robot:
  ucode: "robot_001"                    # 机器人唯一标识
  version: "1.0.0"                      # 版本号
  client_type: "robot"                  # 客户端类型

# 服务器配置
server:
  url: "ws://localhost:8000/ws/control" # WebSocket服务器地址
  connect_timeout: 30                   # 连接超时时间（秒）
  read_timeout: 30                      # 读取超时时间（秒）
  write_timeout: 10                     # 写入超时时间（秒）

# 心跳配置
heartbeat:
  interval: 10                          # 心跳间隔（秒）
  timeout: 10                           # 心跳超时（秒）

# 状态上报配置
status:
  interval: 10                          # 状态上报间隔（秒）
  enable_simulation: true               # 启用状态模拟

# 日志配置
logging:
  level: "info"                         # 日志级别 (debug, info, warn, error)
  format: "json"                        # 日志格式 (json, console)
  output: "stdout"                      # 输出目标 (stdout, stderr, file)
  file_path: ""                         # 日志文件路径（留空表示不输出到文件）
  max_size: 100                         # 最大文件大小（MB）
  max_backups: 3                        # 最大备份数
  max_age: 28                           # 最大保存天数

# 重连配置
reconnect:
  enabled: true                         # 启用自动重连
  max_attempts: 5                       # 最大重连次数
  initial_delay: 1                      # 初始重连延迟（秒）
  max_delay: 60                         # 最大重连延迟（秒）
  backoff_multiplier: 2.0               # 退避倍数

# 安全配置
security:
  enable_tls: false                     # 启用TLS
  skip_verify: false                    # 跳过证书验证
  auth_token: ""                        # 认证令牌

# 性能配置
performance:
  message_buffer_size: 1000             # 消息缓冲区大小
  worker_pool_size: 4                   # 工作池大小
  enable_metrics: false                 # 启用性能指标 