server:
  port: 8000
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s

janus:
  websocket_url: "ws://localhost:8188"
  http_url: "http://localhost:8088"
  stream_id: 1

robot:
  websocket_url: "ws://localhost:9090"
  control_timeout: 100ms
  max_retries: 3

logging:
  level: "info"
  format: "json"
  output: "stdout"

security:
  enable_cors: true
  allowed_origins:
    - "*"
  api_key_required: false 